---
- name: pull latest code from git
  git:
    repo: ssh://git@github.com/HanxunHuangLemonBear/COMP90024-2019S1-Team7.git
    key_file: /home/ubuntu/.ssh/GitHub
    update: yes
    dest: '{{ remote_working_directory }}'
    force: yes