---
- hosts: dbServers
  vars_files:
    - host_vars/remote_vars.yaml
  gather_facts: true
  roles:
    - role: setup-couchdb

- hosts: dbMaster
  vars_files:
    - host_vars/remote_vars.yaml
  gather_facts: true
  roles:
    - role: setup-couchdb-cluster