- hosts: localhost
  #vars:
  #  ansible_python_interpreter: /Users/jade/Developer-Tool/anaconda3/bin/python3
  vars_files:
    - host_vars/local_vars.yaml
  gather_facts: true

  roles:
    - role: common
    - role: show-images
    - role: create-volume
    - role: create-security-group
    - role: create-instance
    # - role: create-volume-snapshot  # not necessary

