---
# - hosts: localhost
#   gather_facts: true

#   roles:
#     - role: authorized-key-pairs


- hosts: localhost
  vars_files:
    - host_vars/local_vars.yaml
  gather_facts: true
  roles:
    - role: set-proxy-enviroment