---
- hosts: localhost
  vars:
    ansible_python_interpreter: /Users/jade/Developer-Tool/anaconda3/bin/python3
  vars_files:
    - host_vars/mrc.yaml
  gather_facts: true
  roles:
    - role: set-proxy-enviroment